### ISSUE TITLE
Styled Input 오류 여부 확인

### ISSUE THREAD

**Issue by Velo248** [SmallMarket-Project/frontend#40]
```
const sampleItem = [
        { id: 1, value: "value1" },
        { id: 2, value: "value2" },
        { id: 3, value: "value3" },
        { id: 4, value: "value4" },
        { id: 5, value: "value5" },
    ]
```
위는 샘플입니다.

```
                {sampleItem.map((item) => (
                    <Input
                        key={item.id}
                        type="checkbox"
                        value={item.value}
                    ></Input>
                ))}
```

위처럼 Input을 체크박스로 사용하려고 합니다. 그러나 체크는 가능하지만 value에 들어가는 문자열들이 출력 되지 않습니다.

![image](https://user-images.githubusercontent.com/89900244/190338434-e3ec9a2b-0215-4dba-a617-fb036eba1ccb.png)
사진과 같이 나옵니다.

혹시나 하고 type 속성을 기본으로 돌리니
![image](https://user-images.githubusercontent.com/89900244/190338638-80d5b130-0ee4-4d9d-b848-70bcd63fbf0c.png)
정상적으로 작동합니다.
제가 반복을 잘못하고 있습니까? 아니면 오류입니까?

**Comment by vpvm96** [comment]
# CheckBox

- checkbox의 경우 옆에 text를 추가할 수 없습니다.
- <label>태그를 이용하시면 좋을 것 같습니다.
- 혹은 LabeledInput 컴포넌트를 이용하시는 것도 좋은 방법일 것 같아요.

**Comment by Velo248** [comment]
> # CheckBox
> * checkbox의 경우 옆에 text를 추가할 수 없습니다.
> * 태그를 이용하시면 좋을 것 같습니다.
> * 혹은 LabeledInput 컴포넌트를 이용하시는 것도 좋은 방법일 것 같아요.

애초에 불가능한 요소 접근이었군요. 제가 부족했네요 감사합니다.
다른 LabeledInput도 고려하였으나 한 줄의 레이아웃에서 출력 되는 것을 생각하고 있어서
직접 커스텀 하겠습니다.
