### ISSUE TITLE
ErrorUtil관련

### ISSUE THREAD

**Issue by Velo248** [SmallMarket-Project/frontend#68]
ErrorUtil중 배열의 최소 길이를 검사하는 메소드
```
FoodItemListType.createFoodItemListType = function (arr) {
    ErrorUtil.assert(arr.length > 1, "Array size > 1")
    arr.every((a) => ErrorUtil.instanceCheck(a, ItemType))
    return new _FoodItemListType(arr)
}
```
위 코드는 아이템 검색 결과가 1개일 경우 ( 현재 coffee를 검색한 것에 대해)
오류로 잡혀버린다.

해당 유틸 내용
```
ErrorUtil.assert(arr.length > 1, "Array size > 1")
```
을 아래와 같이
```
ErrorUtil.assert(arr.length >= 1, "Array size > 1")
```
변경해도 문제가 없는지? 불가능하다면 다른방법을 모르겠다.

**Comment by Velo248** [comment]
추가로 검색결과가 존재하지 않을 경우 해당 유틸을 우회하거나 무시하는 방법이 있습니까?
productContainer에서 결과가 존재하지 않는다면 특정 문장을 띄어주는 등의 행동으로 사용자에게 결과 오류를 알려주는게 좋다고 생각합니다.

**Comment by Velo248** [comment]
```
if (!searchedItem.length) return []
```
만약 검색내역이 없다면 빈 배열을 리턴하고 Container에서 문구를 출력해주는 것이 우리 코드 방식을 무시합니까?

**Comment by FoxMon** [comment]
```js
ErrorUtil.assert(arr.length < 1, "Array size > 1")
```
이렇게 해도 되겟네여

**Comment by Velo248** [comment]
> ```js
> ErrorUtil.assert(arr.length < 1, "Array size > 1")
> ```
> 
> 이렇게 해도 되겟네여

그럴 경우 검색 결과가 역으로 2개 이상일 때, 검출이됩니다.
>= 으로 우선 수정하였습니다.
